fs = require("fs");
http = require('http');
express = require('express');
cookieParser = require('cookie-parser')
session=require('express-session')
fs = require("fs");
MongoStore = require('connect-mongo')(session);
helpers = require('./helpers.js')
serverFunctions = require('./serverFunctions.js')
databaseFunctions = require('./dataBaseFunctions.js')